---
title: "eGRID 2021 Energy Mix"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
```


https://www.visualcapitalist.com/sp/utilities-decarbonization-index/


```{r}
plant_data_cnames <- read_excel("eGRID2021_data.xlsx", sheet = "PLNT21", skip = 1, n_max = 0) %>% 
  names()

plant_data <- read_excel("eGRID2021_data.xlsx", sheet = "PLNT21", skip = 2, col_names = plant_data_cnames)

plant_data <- plant_data %>% 
  mutate_if(is.numeric, ~replace_na(., 0))

plant_data

```

Energy and Emissions by Operator

```{r}

(operator_totals <- plant_data %>% 
  #filter(PSTATABB == "PA") %>% 
  group_by(OPRNAME, OPRCODE, ISORTO) %>% #, PLPRMFL, PLFUELCT) %>% 
  summarize(total_generation = sum(PLNGENAN), total_capacity = sum(NAMEPCAP), coal_generation = sum(PLGENACL), oil_generation = sum(PLGENAOL), gas_generation = sum(PLGENAGS), nuclear_generation = sum(PLGENANC), hydro_generation = sum(PLGENAHY), biomass_generation = sum(PLGENABM), wind_generation = sum(PLGENAWI), solar_generation = sum(PLGENASO), geothermal_generation = sum(PLGENAGT), other_fossil_generation = sum(PLGENAOF), other_generation = sum(PLGENAOP), renewables_generation = sum(PLGENATR), nox_emissions =  sum(PLNOXAN), so2_emissions = sum(PLSO2AN), co2_emissions = sum(PLCO2AN), ch4_emissions = sum(PLCH4AN), co2_eq_emissions = sum(PLCO2EQA)) %>% 
   mutate(renewables_pct = renewables_generation/total_generation, fossil_fuel_pct = (coal_generation + oil_generation + gas_generation + other_fossil_generation)/total_generation, co2_eq_rate = co2_eq_emissions/total_generation) %>% 
   arrange(desc(total_generation)) %>%
  mutate_if(is.numeric, round, 3) %>% 
   relocate(c(renewables_pct, fossil_fuel_pct, co2_eq_rate), .after = total_generation) #%>% 
   #head(20) 
)

operator_totals %>% 
  mutate(OPRNAME = fct_reorder(OPRNAME, co2_eq_rate)) %>%
#  arrange(desc(co2_eq_rate)) %>% 
#  mutate(OPRNAME=factor(OPRNAME, levels=OPRNAME)) %>% 
  ggplot(aes(x=OPRNAME, y=co2_eq_rate)) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

Energy and Emissions by ISO and State
```{r}

(state_totals <- plant_data %>%
  group_by(PSTATABB) %>% 
  summarize(total_generation = sum(PLNGENAN), total_capacity = sum(NAMEPCAP), coal_generation = sum(PLGENACL), oil_generation = sum(PLGENAOL), gas_generation = sum(PLGENAGS), nuclear_generation = sum(PLGENANC), hydro_generation = sum(PLGENAHY), biomass_generation = sum(PLGENABM), wind_generation = sum(PLGENAWI), solar_generation = sum(PLGENASO), geothermal_generation = sum(PLGENAGT), other_fossil_generation = sum(PLGENAOF), other_generation = sum(PLGENAOP), renewables_generation = sum(PLGENATR), nox_emissions =  sum(PLNOXAN), so2_emissions = sum(PLSO2AN), co2_emissions = sum(PLCO2AN), ch4_emissions = sum(PLCH4AN), co2_eq_emissions = sum(PLCO2EQA)) %>% 
   mutate(renewables_pct = renewables_generation/total_generation, fossil_fuel_pct = (coal_generation + oil_generation + gas_generation + other_fossil_generation)/total_generation, co2_eq_rate = co2_eq_emissions/total_generation) %>% 
   arrange(desc(co2_eq_rate)) %>%
  mutate_if(is.numeric, round, 3) %>% 
   relocate(c(renewables_pct, fossil_fuel_pct, co2_eq_rate), .after = total_generation)
)


(iso_totals <- plant_data %>%
  group_by(ISORTO) %>% 
  summarize(total_generation = sum(PLNGENAN), total_capacity = sum(NAMEPCAP), coal_generation = sum(PLGENACL), oil_generation = sum(PLGENAOL), gas_generation = sum(PLGENAGS), nuclear_generation = sum(PLGENANC), hydro_generation = sum(PLGENAHY), biomass_generation = sum(PLGENABM), wind_generation = sum(PLGENAWI), solar_generation = sum(PLGENASO), geothermal_generation = sum(PLGENAGT), other_fossil_generation = sum(PLGENAOF), other_generation = sum(PLGENAOP), renewables_generation = sum(PLGENATR), nox_emissions =  sum(PLNOXAN), so2_emissions = sum(PLSO2AN), co2_emissions = sum(PLCO2AN), ch4_emissions = sum(PLCH4AN), co2_eq_emissions = sum(PLCO2EQA)) %>% 
   mutate(renewables_pct = renewables_generation/total_generation, fossil_fuel_pct = (coal_generation + oil_generation + gas_generation + other_fossil_generation)/total_generation, co2_eq_rate = co2_eq_emissions/total_generation) %>% 
   arrange(desc(co2_eq_rate)) %>%
  mutate_if(is.numeric, round, 3) %>% 
   relocate(c(renewables_pct, fossil_fuel_pct, co2_eq_rate), .after = total_generation)
)


```

```{r}

```



Ideas
- totals by operator/utility/balancing authority(ISO)
- renewables breakdown by operator/utility
- simple shiny dashboard with sortables
- map using lat/long 
- Shiny map dashboard of states/plants with show coal, nuclear, etc. options
- 
